const textarea = document.getElementById("text");
const counter = document.getElementById("wordCounter");
const analyzeBtn = document.getElementById("analyzeBtn");
const resultBox = document.getElementById("result");
const infoMessage = document.getElementById("infoMessage");

const MIN_WORDS = 20;
let hasResult = false;

textarea.addEventListener("input", updateCounter);

function updateCounter() {
    const words = textarea.value.trim().split(/\s+/).filter(Boolean).length;

    if (hasResult) {
        resultBox.innerHTML = "";
        infoMessage.style.display = "block";
        infoMessage.innerHTML =
            "⚠️ Text changed — previous analysis has been cancelled.";
        hasResult = false;
    }

    if (words >= MIN_WORDS) {
        counter.innerHTML = `Words counter: <strong>${words}</strong> / ${MIN_WORDS} <span class="ok">✔</span>`;
        analyzeBtn.disabled = false;
    } else {
        counter.innerHTML = `Words counter: <strong>${words}</strong> / ${MIN_WORDS} <span class="bad">❌</span>`;
        analyzeBtn.disabled = true;
    }
}

function clearAll() {
    textarea.value = "";
    resultBox.innerHTML = "";
    infoMessage.style.display = "none";
    analyzeBtn.disabled = true;
    hasResult = false;
    updateCounter();
}

function generateExample() {
    textarea.value =
        "Artificial intelligence has rapidly evolved in recent years, transforming the way people interact with technology. " +
        "Modern AI systems can analyze data, understand language, and generate human-like text with impressive accuracy.";

    textarea.dispatchEvent(new Event("input"));
}

async function analyze() {
    const text = textarea.value.trim();
    if (text.split(/\s+/).length < MIN_WORDS) return;

    infoMessage.style.display = "none";
    resultBox.innerHTML = `
        <div class="result-card">
            <div class="model">
                <strong>Transformer</strong>
                <div class="progress">
                    <div class="progress-fill" id="bar-transformer"></div>
                </div>
            </div>

            <div class="model">
                <strong>Logistic Regression</strong>
                <div class="progress">
                    <div class="progress-fill" id="bar-logistic"></div>
                </div>
            </div>
        </div>
    `;

    try {
        const response = await fetch("http://127.0.0.1:8000/analyze", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ text })
        });

        const data = await response.json();
        animateResult(data);

    } catch {
        resultBox.innerHTML =
            "<div class='result-card'>Cannot connect to backend.</div>";
    }
}

/* ===========================
   SMOOTH CALIBRATION ANIMATION
   =========================== */

function animateResult(data) {
    const tProb = Math.round(data.transformer.ai_probability * 100);
    const lProb = Math.round(data.logistic_regression.ai_probability * 100);

    animateBar(document.getElementById("bar-transformer"), tProb);
    animateBar(document.getElementById("bar-logistic"), lProb);

    setTimeout(() => {
        showFinalVerdict(tProb, lProb);
        hasResult = true;
    }, 2600);
}

function animateBar(bar, target) {
    let startTime = null;
    const loadDuration = 800;       // smooth load
    const wobbleDuration = 1400;    // calibration
    const wobbleRange = 5;

    function animate(timestamp) {
        if (!startTime) startTime = timestamp;
        const elapsed = timestamp - startTime;

        // PHASE 1 – smooth load
        if (elapsed < loadDuration) {
            const progress = elapsed / loadDuration;
            bar.style.width = `${progress * target}%`;
        }

        // PHASE 2 – smooth wobble near result
        else if (elapsed < loadDuration + wobbleDuration) {
            const t = elapsed - loadDuration;
            const oscillation =
                Math.sin(t / 120) * wobbleRange;
            bar.style.width = `${target + oscillation}%`;
        }

        // PHASE 3 – stabilize
        else {
            bar.style.width = `${target}%`;
            return;
        }

        requestAnimationFrame(animate);
    }

    requestAnimationFrame(animate);
}

function showFinalVerdict(tProb, lProb) {
    const finalAI = (tProb + lProb) / 2 >= 50;

    resultBox.innerHTML += `
        <div class="final">
            Analysis result:<br>
            <strong>
                ${finalAI
            ? "🤖 This text was generated by AI"
            : "🧑 This text was written by a human"}
            </strong>
        </div>
    `;
}
